name: commit_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the current repository (your repo)
      - uses: actions/checkout@v3
        with:
          path: my-repo

      # Step 2: Checkout the external repository
      - uses: actions/checkout@v3
        with:
          repository: 'abystoma/external-workflow'
          ref: '3eb718710f20d7df6874acdc41e189a2ae4182f5'
          path: external-repo

      # Step 3: Access the greeting.txt from your repo
      - name: Greetings
        run: echo "$(cat my-repo/greeting.txt)"

