name: commit_checkout
on: [push]

jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      # Checkout your own repo (default to workspace root)
      - uses: actions/checkout@v3

      # Checkout external repo into 'external-repo' folder
      - uses: actions/checkout@v3
        with:
          repository: 'abystoma/external-workflow'
          ref: '3eb718710f20d7df6874acdc41e189a2ae4182f5'
          path: external-repo

      # Read greeting.txt from your repo root
      - name: Greetings
        run: |
          echo "Greeting text:"
          cat greeting.txt
